let devices = [
    "ORACLE_US_CA_San_Jose_F0_ROUTER2",
    "ORACLE_US_CA_San_Jose_F0_ROUTER1",
    "ORACLE_US_CA_San_Jose_F0_SW_Core1",
    "ORACLE_US_CA_San_Jose_F0_SW_Core2",
    "ORACLE_US_CA_San_Jose_F0_SW_Multilayer_Distribution1",
    "ORACLE_US_CA_San_Jose_F0_SW_Multilayer_Distribution2",
    "ORACLE_US_CA_San_Jose_F3_SW_Access",
    "ORACLE_US_CA_San_Jose_F2_SW_Access",
    "ORACLE_US_CA_San_Jose_F1_SW_Access",
    "ORACLE_US_CA_San_Jose_F0_SW_Access_SERVERS",
    
    "ORACLE_US_AZ_Phoenix_F0_ROUTER1",
    "ORACLE_US_AZ_Phoenix_F0_ROUTER2",
    "ORACLE_US_AZ_Phoenix_F0_SW_Core1",
    "ORACLE_US_AZ_Phoenix_F0_SW_Core2",
    "ORACLE_US_AZ_Phoenix_F0_SW_Multilayer_Distribution1",
    "ORACLE_US_AZ_Phoenix_F0_SW_Multilayer_Distribution2",
    "ORACLE_US_AZ_Phoenix_F0_SW_Multilayer_Distribution3",
    "ORACLE_US_AZ_Phoenix_F0_SW_Access_SERVERS",
    "ORACLE_US_AZ_Phoenix_F1_SW_Access",
    "ORACLE_US_AZ_Phoenix_F2_SW_Access",
    "ORACLE_US_AZ_Phoenix_F3_SW_Access",
    "ORACLE_US_AZ_Phoenix_F4_SW_Access",
    "ORACLE_US_AZ_Phoenix_F5_SW_Access",
    "ORACLE_US_AZ_Phoenix_F6_SW_Access",
    
    "ORACLE_US_VA_Ashburn_F3_SW",
    "ORACLE_US_VA_Ashburn_F2_SW",
    "ORACLE_US_VA_Ashburn_F1_SW",
    "ORACLE_US_VA_Ashburn_F0_SW_Multilayer",
    "ORACLE_US_VA_Ashburn_F0_SW_SERVERS",
    "ORACLE_US_VA_Ashburn_F0_ROUTER",
    
    "ORACLE_EU_ES_Madrid_F3_SW",
    "ORACLE_EU_ES_Madrid_F2_SW",
    "ORACLE_EU_ES_Madrid_F1_SW",
    "ORACLE_EU_ES_Madrid_F0_SW_Multilayer",
    "ORACLE_EU_ES_Madrid_F0_SW_SERVERS",
    "ORACLE_EU_ES_Madrid_F0_ROUTER",
    
    "ORACLE_EU_DE_Frankfurt_F3_SW",
    "ORACLE_EU_DE_Frankfurt_F2_SW",
    "ORACLE_EU_DE_Frankfurt_F1_SW",
    "ORACLE_EU_DE_Frankfurt_F0_SW_Multilayer",
    "ORACLE_EU_DE_Frankfurt_F0_SW_SERVERS",
    "ORACLE_EU_DE_Frankfurt_F0_ROUTER",
    
    "ORACLE_EU_IT_Milan_F3_SW",
    "ORACLE_EU_IT_Milan_F2_SW",
    "ORACLE_EU_IT_Milan_F1_SW",
    "ORACLE_EU_IT_Milan_F0_SW_Multilayer",
    "ORACLE_EU_IT_Milan_F0_SW_SERVERS",
    "ORACLE_EU_IT_Milan_F0_ROUTER",
    
    "ORACLE_AS_IN_Mumbai_F0_ROUTER2",
    "ORACLE_AS_IN_Mumbai_F0_ROUTER1",
    "ORACLE_AS_IN_Mumbai_F0_SW_Core1",
    "ORACLE_AS_IN_Mumbai_F0_SW_Core2",
    "ORACLE_AS_IN_Mumbai_F0_SW_Multilayer_Distribution2",
    "ORACLE_AS_IN_Mumbai_F0_SW_Multilayer_Distribution1",
    "ORACLE_AS_IN_Mumbai_F3_SW_Access",
    "ORACLE_AS_IN_Mumbai_F2_SW_Access",
    "ORACLE_AS_IN_Mumbai_F1_SW_Access",
    "ORACLE_AS_IN_Mumbai_F0_SW_Access_SERVERS",
    
    "ORACLE_AU_AU_Sydney_F0_ROUTER2",
    "ORACLE_AU_AU_Sydney_F0_ROUTER1",
    "ORACLE_AU_AU_Sydney_F0_SW_Core1",
    "ORACLE_AU_AU_Sydney_F0_SW_Core2",
    "ORACLE_AU_AU_Sydney_F0_SW_Multilayer_Distribution1",
    "ORACLE_AU_AU_Sydney_F0_SW_Multilayer_Distribution2",
    "ORACLE_AU_AU_Sydney_F3_SW_Access",
    "ORACLE_AU_AU_Sydney_F2_SW_Access",
    "ORACLE_AU_AU_Sydney_F1_SW_Access",
    "ORACLE_AU_AU_Sydney_F0_SW_Access_SERVERS"
];

for (let deviceName of devices) {
    configureIosDevice(deviceName, "line vty 0 4\nlogin local\ntransport input ssh\nusername admin password 1234\nip domain-name oracle.com\ncrypto key generate rsa general-keys modulus 1024");
}
